import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavProvider from "./components/NavProvider";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Biraj Shrestha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <Head>
        <title>Biraj Shrestha Portfolio</title>
        <meta property="og:title" content="Biraj Shrestha Portfolio" />
        <meta
          property="og:description"
          content="React, Next.js, Tailwind CSS projects showcase"
        />
        <meta property="og:image" content="/public/avtar-dz7QYeYu.png" />
        <meta property="og:url" content="https://www.shresthabiraj.com.np/" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      >
        <NavProvider>{children}</NavProvider>
      </body>
    </html>
  );
}
